### ISSUE TITLE
Slow screen buffer content update

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/mosh-go#1]
Remote host data and user input is showed with too long screen update time interval.

**Comment by nikitar020** [comment]
Is this still actual? I think with the latest changes the mosh client has become much faster.

**Comment by MaxRis** [comment]
@nikitar020 that was improved by "dirty" workaround https://github.com/jumptrading/mosh-go/commit/10ae142582e583004fe21d7a2aac3d0402497316
I haven't seen increase in CPU usage, but it has sense to figure out how to avoid fast looping (original implementation seems awaits in `select` call for the activity from one of observed fds; but in our case, user input is not fd, for example; and maybe other differences are in place)

**Comment by MaxRis** [comment]
once we will get the app to the stage when each ms in delay will be significant (to reach the same performance as mosh on unix has), this Issue might be very important.

**Comment by MaxRis** [comment]
Resolved by https://github.com/jumptrading/mosh-go/pull/19
