### ISSUE TITLE
tmux session selection screen contains incorrectly handled characters artifacts

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/mosh-go#11]
![2019-03-30_21-01-59-tmux-encoding-issue](https://user-images.githubusercontent.com/1928902/55280510-258bd480-532f-11e9-80a3-54ed508c4f7d.png)

**Comment by nikitar020** [comment]
This is releated not only to `tmux`. It seems that the problem is that internally mosh_client uses UTF8 but the Windows console does not support UTF8 natively (it supports only UTF16 or ANSI), so it is needs to transcode strings before sending them to the console.

**Comment by MaxRis** [comment]
@nikitar020 thanks, it makes sense, will check for it.
