### ISSUE TITLE
Socket duplication doesn't work

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/mosh-go#2]
[Socket duplication call](https://github.com/jumptrading/mosh-go/blob/mosh-client/client/mosh-client/network/network.cc#L725) fails and prevents application to copy `Connection::Socket` objects and be collected in std collection in the designed way.

**Comment by nikitar020** [comment]
Has been fixed by this commit: https://github.com/jumptrading/mosh-go/commit/8ccc6f489548352e89106e8d6c9a279ad208eb34 (accidentally did not make a PR and committed directly).
